apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: Kustomize-app

commonLabels:
  app: kustomize-app
  owner: Yogitha

namePrefix: app1-

resources:
- app1-dep-svc.yaml
