# templates/applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  {{- range $app := .Values.apps }}
  - matrix:
      generators:
      - list:
          elements:
          - app-name: {{ $app.appname }}
            wave-no: {{ $app.wave }}
      - list:
          elements:
          - env-name: {{ $app.env }}
            server-name: {{ $app.server }}   
  {{- end }}
  template:
    metadata:
      name: '{{.app-name}}-guestbook-{{.env-name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "{{.wave-no}}"
        argocd.argoproj.io/sync-options: ApplyOnly=true
    spec:
      syncPolicy:
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ApplyOnly=true
      project: default
      source:
        repoURL: https://github.com/yogithakakarla/kustomize-multiple-apps.git
        targetRevision: HEAD
        path: common/{{.app-name}}/overlays/{{.env-name}}
      destination:
        server: '{{.server-name}}'
        namespace: '{{.env-name}}-{{.app-name}}'
