# templates/applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-multipleapps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:  
  - list:
      elements:
      {{- range .Values.apps }}
      - appnameargo: {{ .appname }}
        waveargo: {{ .wave }}
        envargo: {{ .env }}
        serverargo: {{ .server }}   
      {{- end }}
  template:
    metadata:
      name: "{{`{{ .appnameargo }}{{ .envargo }}`}}"
      annotations:
        argocd.argoproj.io/sync-wave: '{{.waveargo}}'
        argocd.argoproj.io/sync-options: ApplyOnly=true
    spec:
      syncPolicy:
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ApplyOnly=true
      project: default
      source:
        repoURL: https://github.com/yogithakakarla/kustomize-multiple-apps.git
        targetRevision: HEAD
        path: {{.appnameargo}}/overlays/{{.envargo}}

      destination:
        server: '{{.serverargo}}'
        namespace: '{{.envargo}}-{{.appnameargo}}'
