
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  {{- range $wave, $apps := .Values }}
  - matrix:
      generators:
      - list:
          elements:
          {{- range $apps }}
          - appname: {{ .appname }}
            wave: {{ .wave }}
          {{- end }}
      - list:
          elements:
          {{- range $env := .env }}
          - env: {{ . }}
            server: https://kubernetes.default.svc
          {{- end }}
  {{- end }}
  template:
    metadata:
      name: '{{.appname}}-guestbook-{{.env}}'
      annotations:
        argocd.argoproj.io/sync-wave: "{{.wave}}"
        argocd.argoproj.io/sync-options: ApplyOnly=true
    spec:
      syncPolicy:
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ApplyOnly=true
      project: default
      source:
        repoURL: https://github.com/yogithakakarla/kustomize-multiple-apps.git
        targetRevision: HEAD
        path: common/{{.appname}}/overlays/{{.env}}
      destination:
        server: '{{.server}}'
        namespace: '{{.env}}-{{.appname}}'
