apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - appname: app1 
          - appname: app2   
      - list:
          elements:
          - env: dev
            server: https://kubernetes.default.svc
          - env: prod
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.appname}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/yogithakakarla/kustomize-multiple-apps.git
        targetRevision: HEAD
        path: common/{{.appname}}/overlays/{{.env}}
      destination:
        server: '{{.server}}'
        namespace: '{{.env}}'
