apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:

  name: guestboo1k
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - appname: app1 
            wave: 3
          
          - appname: app2 
            wave: 2
     
      - list:
          elements:
          - env: dev
            server: https://kubernetes.default.svc
          - env: prod
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.appname}}-guestbook-{{.env}}'
      annotations:
        argocd.argoproj.io/sync-wave: "{{.wave}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/yogithakakarla/kustomize-multiple-apps.git
        targetRevision: HEAD
        path: common/{{.appname}}/overlays/{{.env}}
      destination:
        server: '{{.server}}'
        namespace: '{{.env}}-{{.appname}}'
