apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/load-generator/

namespace: qa-dev

patches:
- patch: |-
    - op: replace
      path: /spec/externalName
      value: frontend.dev-app2.svc.cluster.local
  target:
    kind: Service
    name: frontend
